server:
  port: 8080
  servlet:
      context-path: /calc-becas
spring:
  datasource:
    url: jdbc:mysql://${HOST_NAME:127.0.0.1}:${BD_PORT:3311}/${BD_NAME:calcbecabd}?useSSL=false
    username: ${BD_USER:dbuser}
    password: ${BD_PASS:dbpassword}
key:
  encode:
    crypto: $#u1!N51*5M412&
location:
  file: /Users/lMarcoss/workspace-leo/ServicioSocial/files-dev/
logging:
  level:
    org:
      springframework:
        web= DEBUG
