server:
  port: 8080
  servlet:
    context-path: /calc-becas
spring:
  datasource:
    url: jdbc:mysql://${HOST_NAME:127.0.0.1}:${BD_PORT:3311}/${BD_NAME:calcbecabd}?useSSL=false
    username: ${BD_USER:dbuser}
    password: ${BD_PASS:dbpassword}
key:
  encode:
    crypto: $#u1!N51*5M412&
location:
  file: ${PATH_FILE_DEV_CALC_UNSIS:/Users/vampiro/workspace-leo/servicio-social/file-dev/}

prop:
  sistema:
    horarios:
      url: https://json-horarios.herokuapp.com/horarios/api
      api:
        carreras:
          vigentes: /carreras/vigentes
          detallecarrera: /carreras/detalle-carrera
        grupos: /grupos
        periodo:
          actual: /periodo/actual
          lista: /periodo/lista
  security:
    secret:
      key:
        start: 4^%m@=C*&c#L+%
        end: U$|2AT>30!
  carga:
    hrs:
      biblioteca:
        id: 1
        posicion:
          matricula: 1
          nombre: 2
          horas: 3
          celda:
            final: 4
      sala:
        id: 2
        posicion:
          matricula: 1
          nombre: 2
          asistencia:
            inicio: 3
        asistencia:
          asistencia: .
          falta: /
    alumnos:
      alumnos:
        id: 1
        posicion:
          grupo: 0
          matricula: 1
          curp: 2
          apePaterno: 3
          apeMaterno: 4
          nombres: 5
          celda:
            final: 6
